name: Build ColorOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: sudo apt update && sudo apt install -y nasm gcc qemu-system-x86

    - name: Compile
      run: |
        nasm -f bin src/boot.asm -o boot.bin
        nasm -f bin src/drivers.asm -o drivers.bin
        gcc -m32 -ffreestanding -nostdlib -c src/files.c -o files.o
        ld -m elf_i386 -Ttext 0xA000 files.o -o files.elf
        objcopy -O binary files.elf files.bin
        gcc -m32 -ffreestanding -nostdlib -c src/gui.c -o gui.o
        ld -m elf_i386 -Ttext 0x9000 gui.o -o gui.elf
        objcopy -O binary gui.elf gui.bin
        gcc -m32 -ffreestanding -nostdlib -c src/kernel.c -o kernel.o
        ld -m elf_i386 -Ttext 0x8000 kernel.o -o kernel.elf
        objcopy -O binary kernel.elf kernel.bin

    - name: Create disk
      run: |
        dd if=/dev/zero of=disk.img bs=1024 count=1024
        dd if=boot.bin of=disk.img bs=512 count=1 conv=notrunc
        dd if=kernel.bin of=disk.img bs=512 seek=1 conv=notrunc
        dd if=gui.bin of=disk.img bs=512 seek=2 conv=notrunc
        dd if=drivers.bin of=disk.img bs=512 seek=3 conv=notrunc
        dd if=files.bin of=disk.img bs=512 seek=4 conv=notrunc
        dd if=src/snake.clr of=disk.img bs=512 seek=14 conv=notrunc
        truncate -s 1M disk.img

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: coloros
        path: disk.img
